/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package figuras_geometricas;

import java.awt.Color;

/**
 *
 * @author Daniel
 */
public class DibujaGraficasView extends javax.swing.JFrame {

    /**
     * Creates new form DibujaGraficasView
     */
    public DibujaGraficasView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnDibujaLinea = new javax.swing.JButton();
        Pizarra = new javax.swing.JPanel();
        btnDibujarCuadrado = new javax.swing.JButton();
        btnDibujarCirculo = new javax.swing.JButton();
        btnDibujarRectangulo = new javax.swing.JButton();
        btnDibujarElipse = new javax.swing.JButton();
        btnEliminarDibujo = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnDibujaLinea.setText("Dibujar Linea");
        btnDibujaLinea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDibujaLineaActionPerformed(evt);
            }
        });

        Pizarra.setBackground(new java.awt.Color(0, 0, 0));
        Pizarra.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Pizarra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PizarraMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout PizarraLayout = new javax.swing.GroupLayout(Pizarra);
        Pizarra.setLayout(PizarraLayout);
        PizarraLayout.setHorizontalGroup(
            PizarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 315, Short.MAX_VALUE)
        );
        PizarraLayout.setVerticalGroup(
            PizarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 285, Short.MAX_VALUE)
        );

        btnDibujarCuadrado.setText("Dibujar Cuadrado");
        btnDibujarCuadrado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDibujarCuadradoMouseClicked(evt);
            }
        });

        btnDibujarCirculo.setText("Dibujar Circulo");
        btnDibujarCirculo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDibujarCirculoMouseClicked(evt);
            }
        });

        btnDibujarRectangulo.setText("Dibujar Rectangulo");
        btnDibujarRectangulo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDibujarRectanguloMouseClicked(evt);
            }
        });

        btnDibujarElipse.setText("Dibujar Elipse");
        btnDibujarElipse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDibujarElipseMouseClicked(evt);
            }
        });

        btnEliminarDibujo.setText("Eliminar Dibujo");
        btnEliminarDibujo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEliminarDibujoMouseClicked(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(204, 255, 255));
        jLabel1.setText("Figuras Geometricas");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnDibujarCuadrado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDibujarCirculo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDibujaLinea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDibujarRectangulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDibujarElipse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEliminarDibujo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(Pizarra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(btnDibujaLinea)
                .addGap(18, 18, 18)
                .addComponent(btnDibujarCuadrado)
                .addGap(18, 18, 18)
                .addComponent(btnDibujarCirculo)
                .addGap(18, 18, 18)
                .addComponent(btnDibujarRectangulo)
                .addGap(18, 18, 18)
                .addComponent(btnDibujarElipse)
                .addGap(18, 18, 18)
                .addComponent(btnEliminarDibujo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(Pizarra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDibujarCuadradoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDibujarCuadradoMouseClicked
    Dibujo.HacerCuadro(Pizarra.getGraphics(), 110, 110, 110, 110);
    
    }//GEN-LAST:event_btnDibujarCuadradoMouseClicked

    private void PizarraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PizarraMouseClicked
     
    }//GEN-LAST:event_PizarraMouseClicked

    private void btnDibujaLineaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDibujaLineaActionPerformed
    Dibujo.Hacerlinea(Pizarra.getGraphics(), 110, 110, 220, 220);
    }//GEN-LAST:event_btnDibujaLineaActionPerformed

    private void btnDibujarCirculoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDibujarCirculoMouseClicked
    Dibujo.HacerCirculo(Pizarra.getGraphics(), 110, 110, 110, 110);
    
    }//GEN-LAST:event_btnDibujarCirculoMouseClicked

    private void btnDibujarRectanguloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDibujarRectanguloMouseClicked
    Dibujo.HacerRectangulo(Pizarra.getGraphics(), 130, 90, 130, 90);
  
    }//GEN-LAST:event_btnDibujarRectanguloMouseClicked

    private void btnDibujarElipseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDibujarElipseMouseClicked
    Dibujo.HacerElipse(Pizarra.getGraphics(), 130, 60, 130, 60 );
    }//GEN-LAST:event_btnDibujarElipseMouseClicked

    private void btnEliminarDibujoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarDibujoMouseClicked
    Pizarra.repaint();
        
    }//GEN-LAST:event_btnEliminarDibujoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DibujaGraficasView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DibujaGraficasView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DibujaGraficasView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DibujaGraficasView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DibujaGraficasView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Pizarra;
    private javax.swing.JButton btnDibujaLinea;
    private javax.swing.JButton btnDibujarCirculo;
    private javax.swing.JButton btnDibujarCuadrado;
    private javax.swing.JButton btnDibujarElipse;
    private javax.swing.JButton btnDibujarRectangulo;
    private javax.swing.JButton btnEliminarDibujo;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
